///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryEntity {
/*
{
  "id": "NDBlMDBiY2ItMGNlOC00MmQyLWI4ZjMtYjIwMTM0MmU1Zjk5",
  "name": "Bệnh thường gặp ở trẻ em",
  "description": "Tổng hợp các bài thuốc liên quan tới các bệnh thường gặp ở trẻ em",
  "icon": "",
  "iconType": "lucide",
  "iconSize": null,
  "className": null,
  "isActive": true,
  "code": "BENH_TRE_EM",
  "allowEdit": true,
  "categoryTypeId": "NGRkNzAxY2EtNjhmNi00Nzk4LWFmMjItNTE5YjEyYzg5MGIx",
  "sortOrder": 0,
  "isDefault": false,
  "createBy": "1",
  "createdAt": "2025-07-31T08:19:56.000Z",
  "updatedAt": "2025-07-31T08:20:04.000Z"
} 
*/

  String? id;
  String? name;
  String? description;
  String? icon;
  String? iconType;
  String? iconSize;
  String? className;
  bool? isActive;
  String? code;
  bool? allowEdit;
  String? categoryTypeId;
  int? sortOrder;
  bool? isDefault;
  String? createBy;
  String? createdAt;
  String? updatedAt;

  CategoryEntity({
    this.id,
    this.name,
    this.description,
    this.icon,
    this.iconType,
    this.iconSize,
    this.className,
    this.isActive,
    this.code,
    this.allowEdit,
    this.categoryTypeId,
    this.sortOrder,
    this.isDefault,
    this.createBy,
    this.createdAt,
    this.updatedAt,
  });
  CategoryEntity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    icon = json['icon']?.toString();
    iconType = json['iconType']?.toString();
    iconSize = json['iconSize']?.toString();
    className = json['className']?.toString();
    isActive = json['isActive'];
    code = json['code']?.toString();
    allowEdit = json['allowEdit'];
    categoryTypeId = json['categoryTypeId']?.toString();
    sortOrder = json['sortOrder']?.toInt();
    isDefault = json['isDefault'];
    createBy = json['createBy']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['icon'] = icon;
    data['iconType'] = iconType;
    data['iconSize'] = iconSize;
    data['className'] = className;
    data['isActive'] = isActive;
    data['code'] = code;
    data['allowEdit'] = allowEdit;
    data['categoryTypeId'] = categoryTypeId;
    data['sortOrder'] = sortOrder;
    data['isDefault'] = isDefault;
    data['createBy'] = createBy;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}
