// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRt1APWlAgfOiVynIhzmJqO4N2aZnJ204',
    appId: '1:228679159711:web:3736612bd259ed13feb662',
    messagingSenderId: '228679159711',
    projectId: 'sotaynamduoc',
    authDomain: 'sotaynamduoc.firebaseapp.com',
    storageBucket: 'sotaynamduoc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRt1APWlAgfOiVynIhzmJqO4N2aZnJ204',
    appId: '1:700663881543:android:56546d0fede25cbcfeb662',
    messagingSenderId: '700663881543',
    projectId: 'sotaynamduoc',
    storageBucket: 'sotaynamduoc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZElPHnqewdmbkJrbzA5CnLd6WgrSOcw',
    appId: '1:700663881543:ios:57f26bd2d4cc8b82feb662',
    messagingSenderId: '700663881543',
    projectId: 'sotaynamduoc',
    storageBucket: 'sotaynamduoc.firebasestorage.app',
    iosClientId:
        '228679159711-k41tgofkrglamkn6khb79ttp772ej4ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.sotaynamduoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRt1APWlAgfOiVynIhzmJqO4N2aZnJ204',
    appId: '1:228679159711:ios:3736612bd259ed13feb662',
    messagingSenderId: '228679159711',
    projectId: 'sotaynamduoc',
    storageBucket: 'sotaynamduoc.firebasestorage.app',
    iosClientId:
        '228679159711-k41tgofkrglamkn6khb79ttp772ej4ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.sotaynamduoc',
  );
}
